config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root controller: :articles, action: :index
  
  resources :articles, only: [:show, :new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    redirect_to root_path, notice: "Your article was sucessfully created"
  end


  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<% if user_signed_in?%>
<% @articles.each do |article| %>
  <h1> <%= link_to article.title, article_path(article) %> </h1>
<% end %>
<%= link_to "Write", new_article_path %>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<%else%>
<%= link_to "Login", new_user_session_path%>
<%end%>

app/views/articles/new.html.erb
<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <%= form.submit 'Create Article' %> 
<% end %>

app/views/articles/show.html.erb
<%= @article.id%>
<%= @article.created_at%><br>
<%= @article.title%>
<%= @article.content%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <h2><%= flash[:notice] %></h2>
  </body>
</html>